/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || 'NjM4Tjlzc1l2THhpbVJza2tNZEhaVnpSbTduMWZuTE1GeTRqeUdCaDJ2TT18aG9yaXpvbnRhbGQ4ZWIyLXhtY3NoYXJlZC1kZXYtOTcyNg==',
config.sitecoreApiHost = process.env.SITECORE_API_HOST || '',
config.sitecoreSiteName = process.env.SITECORE_SITE_NAME || 'Bhavin-XMC',
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge',
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en',
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'https://edge.sitecorecloud.io/api/graphql/v1',
config.layoutServiceConfigurationName = process.env.LAYOUT_SERVICE_CONFIGURATION_NAME || 'sxa-jss',
config.publicUrl = process.env.PUBLIC_URL || 'http://localhost:3000',
config.sitecoreEdgeUrl = process.env.SITECORE_EDGE_URL || 'https://edge-platform.sitecorecloud.io',
config.sitecoreEdgeContextId = process.env.SITECORE_EDGE_CONTEXT_ID || '',
config.sites = process.env.SITES || '[{"name":"demo-site","hostName":null,"language":null},{"name":"NextApp","hostName":"*","language":"en"},{"name":"Scholar","hostName":"*","language":"en"},{"name":"daivagna poc","hostName":"*","language":"en"},{"name":"xm-cloud-swati","hostName":"*","language":"en"},{"name":"site-1","hostName":"*","language":"en"},{"name":"Shared","hostName":"difc-experienceedge-shared.vercel.app","language":"en"},{"name":"ExperienceWebsite","hostName":"www.exp.ae","language":"en"},{"name":"Bhavin-XMC","hostName":"*","language":"en"},{"name":"siet1","hostName":"*","language":"en"},{"name":"kpbasics","hostName":"*","language":"en"},{"name":"tusharsite","hostName":"*","language":"en"},{"name":"sc103-xm-demo","hostName":"*","language":"en"},{"name":"site-shared","hostName":"*","language":"en"},{"name":"dsinclair-training","hostName":"*","language":"en"},{"name":"KPBasics","hostName":null,"language":null},{"name":"XmCloudPlayBox","hostName":"localhost:3000","language":"en"},{"name":"DWTC","hostName":"*","language":"en"},{"name":"KPTestA","hostName":"*","language":"en"},{"name":"recaptcha","hostName":"*","language":"en"},{"name":"XM Cloud App","hostName":"*","language":"en"},{"name":"brenttest","hostName":"*","language":"en"},{"name":"SK-Emptysite","hostName":"*","language":"en"},{"name":"Test","hostName":"xmcloudhead.vercel.app","language":"en"},{"name":"xm-cloud-jd","hostName":"*","language":"en"},{"name":"BasicSite","hostName":"*","language":"en"},{"name":"site-one","hostName":"*","language":"en"},{"name":"xm-cloud-rohan","hostName":"*","language":"en"},{"name":"alpesh-test","hostName":"*","language":"en"}]',
module.exports = config;